package com.ukrdroiddev.domain.entities

data class AnimeDataUiEntity(
    val malId: Int,
    val url: String,
    val images: AnimeImageUiEntity,
    val trailer: TrailerUiEntity,
    val approved: Boolean,
    val title: String,
    val titleEnglish: String?,
    val titleJapanese: String?,
    val titleSynonyms: List<String>,
    val type: String,
    val source: Source?,
    val episodes: Int,
    val status: AnimeStatus,
    val airing: Boolean,
    val duration: String,
    val rating: String,
    val score: Float,
    val scoredBy: Int,
    val rank: Int,
    val popularity: Int,
    val members: Int,
    val favorites: Int,
    val synopsis: String?,
    val background: String?,
    val season: String?,
    val year: Int?,
    val producers: List<ProducerUiEntity>,
    val studios: List<StudioUiEntity>,
    val genres: List<GenreUiEntity>,
    val explicitGenres: List<ExplicitGenreUiEntity>,
    val themes: List<ThemeUiEntity>,
    val demographics: List<DemographicUIEntity>
)
